version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: flix-api
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: flix-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_USER: "myuser"
      POSTGRES_DB: "core"

volumes:
  pgdata: