version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: flix-api
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py migrate && python manage.py runserver"
    volumes:
      - .:/app
