services:
  sge_web:
    build: .
    container_name: sge_web
    ports:
      - 8000:8000
    depends_on:
      - sge_db

  sge_db:
    image: postgres:15
    container_name: sge_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=value
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sge

volumes:
  postgres_data:
